### ISSUE TITLE
External data source

### ISSUE THREAD

**Issue by edouard-lopez** [adamoudad/tifinagh-transliterator#1]
Hello @adamoudad!
I see you are planning to use the JSON file I created in [parlr/tifinagh-data](https://github.com/parlr/tifinagh-data), that's great!

The file is based on the content of [Wikipedia's article Tifinagh](https://fr.wikipedia.org/w/index.php?title=Tifinagh&oldid=176294814#Normalisation_internationale_(Unicode)). However, I'm not a tifinagh speaker myself, so if you find any mistakes please let me know, so I can fix it.

Cheers!

**Comment by adamoudad** [comment]
Thanks for your work on this @edouard-lopez !
There are few resources on tifinagh and your JSON file was the best I could find. The content looks good, I did not find any mistake.
Best.
